#!/usr/bin/env node
/**
 * XClawRouter CLI
 *
 * Standalone proxy for deployed setups where the proxy needs to survive gateway restarts.
 *
 * Usage:
 *   npx @blockrun/xclawrouter              # Start standalone proxy
 *   npx @blockrun/xclawrouter --version    # Show version
 *   npx @blockrun/xclawrouter --port 8402  # Custom port
 *
 * For production deployments, use with PM2:
 *   pm2 start "npx @blockrun/xclawrouter" --name clawrouter
 */

import { startProxy, getProxyPort } from "./proxy.js";
import { VERSION } from "./version.js";
import {
  resolveOrGenerateWalletKey,
  resolvePaymentChain,
  recoverWalletFromMnemonic,
  savePaymentChain,
  formatAgenticWalletStatus,
  detectOnchainosWallet,
  OnchainOsRequiredError,
} from "./auth.js";
import { OnchainOsAdapter, resolveOnchainosBin } from "./onchainos-adapter.js";
import { execSync, execFileSync } from "node:child_process";
import { homedir } from "node:os";
import { createInterface } from "node:readline/promises";
import { getSolanaAddress } from "./wallet.js";
import { generateReport } from "./report.js";
import { formatRecentLogs } from "./stats.js";
import { runDoctor } from "./doctor.js";
import { PARTNER_SERVICES } from "./partners/index.js";

function printHelp(): void {
  console.log(`
XClawRouter v${VERSION} - Smart LLM Router

Usage:
  xclawrouter [options]
  xclawrouter setup                     # Interactive OKX Agentic Wallet onboarding
  xclawrouter status                    # Live proxy status (wallet, balance, chain)
  xclawrouter wallet                    # Wallet details + balance
  xclawrouter models                    # List available models
  xclawrouter stats [--days <n>]        # Usage stats (default: 7 days)
  xclawrouter doctor [opus] [question]
  xclawrouter partners [test]
  xclawrouter report [daily|weekly|monthly] [--json]
  xclawrouter logs [--days <n>]

Options:
  --version, -v     Show version number
  --help, -h        Show this help message
  --port <number>   Port to listen on (default: ${getProxyPort()})

Query Commands (talk to running proxy on localhost:${getProxyPort()}):
  status            Proxy status: wallet, balance, payment chain
  wallet            Wallet addresses + USDC balance
  models            List all available models with pricing
  stats             Usage breakdown: requests, cost, top models
  stats --days 14   Custom time range (max 30 days)
  cache             Response cache stats (hit rate, size)

Management Commands:
  setup             Interactive OKX Agentic Wallet onboarding (email login)
  doctor            AI-powered diagnostics (default: Sonnet ~$0.003)
  doctor opus       Use Opus for deeper analysis (~$0.01)
  logs              Per-request breakdown: model, cost, latency, status
  logs --days 7     Show last 7 days of requests (default: 1 day)
  partners          List available partner APIs with pricing
  partners test     Test partner API endpoints (expect 402 = alive)
  wallet recover    Restore wallet.key from mnemonic (if generated by XClawRouter)
  chain solana      Switch to Solana (persists)
  chain base        Switch to Base EVM (persists)

Environment Variables:
  BLOCKRUN_WALLET_KEY              Override wallet key (legacy local-key path)
  BLOCKRUN_PROXY_PORT              Default proxy port (default: 8402)
  XCLAWROUTER_USE_LOCAL_WALLET=1   Opt into legacy local BIP-39 wallet generation
                                   (default: require OKX Agentic Wallet via onchainos)
  XCLAWROUTER_ONCHAINOS_BIN        Override onchainos CLI path

For more info: https://blockrun.ai/clawrouter.md
`);
}

/** Query the running proxy HTTP API */
async function queryProxy(path: string, port: number): Promise<unknown> {
  const res = await fetch(`http://127.0.0.1:${port}${path}`);
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${await res.text()}`);
  return res.json();
}

async function cmdStatus(port: number): Promise<void> {
  try {
    const data = (await queryProxy("/health?full=true", port)) as Record<string, unknown>;
    console.log(`\nClawRouter Status (port ${port})\n`);
    console.log(`  Status:        ${data.status}`);
    console.log(`  Payment Chain: ${data.paymentChain}`);
    console.log(`  EVM Wallet:    ${data.wallet}`);
    if (data.solana) console.log(`  Solana Wallet: ${data.solana}`);
    console.log(`  Balance:       ${data.balance ?? "unknown"}`);
    if (data.isLow) console.log(`  ⚠ Balance is low`);
    if (data.isEmpty) console.log(`  ⚠ Balance is empty — using free models`);
    if (data.upstreamProxy) console.log(`  Upstream Proxy: ${data.upstreamProxy}`);
    console.log();
  } catch {
    console.error(`✗ Cannot connect to XClawRouter on port ${port}`);
    console.error(`  Is the proxy running? Start with: npx @blockrun/xclawrouter`);
    process.exit(1);
  }
}

async function cmdWallet(port: number): Promise<void> {
  try {
    const data = (await queryProxy("/health?full=true", port)) as Record<string, unknown>;
    console.log(`\nClawRouter Wallet\n`);
    console.log(`  Payment Chain: ${data.paymentChain}`);
    console.log();
    console.log(`  Base (EVM):`);
    console.log(`    Address: ${data.wallet}`);
    console.log(`    Fund:    https://basescan.org/address/${data.wallet}`);
    if (data.solana) {
      console.log();
      console.log(`  Solana:`);
      console.log(`    Address: ${data.solana}`);
      console.log(`    Fund:    https://solscan.io/account/${data.solana}`);
    }
    console.log();
    console.log(`  Balance: ${data.balance ?? "unknown"} (USDC)`);
    if (data.isEmpty) console.log(`  ⚠ Empty — fund wallet or use free models`);
    console.log();
  } catch {
    console.error(`✗ Cannot connect to XClawRouter on port ${port}`);
    process.exit(1);
  }
}

async function cmdModels(port: number): Promise<void> {
  try {
    const data = (await queryProxy("/v1/models", port)) as {
      data: Array<{ id: string; owned_by?: string }>;
    };
    console.log(`\nAvailable Models (${data.data.length})\n`);

    // Group by provider
    const groups = new Map<string, string[]>();
    for (const m of data.data) {
      const provider = m.id.includes("/") ? m.id.split("/")[0] : "blockrun";
      if (!groups.has(provider)) groups.set(provider, []);
      groups.get(provider)!.push(m.id);
    }

    for (const [provider, models] of groups) {
      console.log(`  ${provider} (${models.length}):`);
      for (const id of models) {
        console.log(`    ${id}`);
      }
      console.log();
    }
  } catch {
    console.error(`✗ Cannot connect to XClawRouter on port ${port}`);
    process.exit(1);
  }
}

async function cmdStats(port: number, days: number): Promise<void> {
  try {
    const data = (await queryProxy(`/stats?days=${days}`, port)) as Record<string, unknown>;
    const stats = data as {
      totalRequests?: number;
      totalCostUsd?: number;
      savedUsd?: number;
      savingsPercent?: number;
      topModels?: Array<{ model: string; requests: number; costUsd: number }>;
    };

    console.log(`\nUsage Stats (last ${days} days)\n`);
    console.log(`  Requests: ${stats.totalRequests ?? 0}`);
    console.log(`  Cost:     $${(stats.totalCostUsd ?? 0).toFixed(4)}`);
    if (stats.savedUsd) {
      console.log(
        `  Saved:    $${stats.savedUsd.toFixed(4)} (${stats.savingsPercent?.toFixed(0) ?? 0}% vs Opus)`,
      );
    }

    if (stats.topModels && stats.topModels.length > 0) {
      console.log();
      console.log(`  Top Models:`);
      for (const m of stats.topModels.slice(0, 10)) {
        console.log(
          `    ${m.model.padEnd(40)} ${String(m.requests).padStart(5)} reqs  $${m.costUsd.toFixed(4)}`,
        );
      }
    }
    console.log();
  } catch {
    console.error(`✗ Cannot connect to XClawRouter on port ${port}`);
    process.exit(1);
  }
}

/**
 * Bootstrap OKX Agentic Wallet for XClawRouter — minimal direct flow,
 * polished CLI presentation.
 *
 * The binary outputs raw JSON for every command (`{"ok":true,...}`). We
 * capture stdio (not inherit) so users don't see the JSON, then surface
 * a clean status line per step. ANSI escapes only — no extra deps.
 */

const ANSI = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  green: "\x1b[32m",
  red: "\x1b[31m",
  yellow: "\x1b[33m",
  cyan: "\x1b[36m",
  magenta: "\x1b[35m",
} as const;
const useColor =
  process.stdout.isTTY && !process.env.NO_COLOR && process.env.TERM !== "dumb";
const c = (color: string, s: string): string => (useColor ? `${color}${s}${ANSI.reset}` : s);
// eslint-disable-next-line no-control-regex
const ANSI_RE = /\x1b\[[0-9;]*m/g;
const stripAnsi = (s: string): string => s.replace(ANSI_RE, "");

function printSetupHeader(): void {
  console.log();
  console.log("  " + c(ANSI.bold + ANSI.cyan, "🦞  XClawRouter — Wallet Setup"));
  console.log("  " + c(ANSI.dim, "OKX Agentic Wallet (onchainos)"));
  console.log();
}

function printSetupSummary(address: string, email: string | undefined): void {
  const lines = [
    c(ANSI.bold + ANSI.green, "✓  Wallet ready"),
    "",
    c(ANSI.dim, "EVM address"),
    c(ANSI.bold, address),
  ];
  if (email) {
    lines.push("");
    lines.push(c(ANSI.dim, "Email   ") + email);
  }
  lines.push(c(ANSI.dim, "Signing ") + "OKX TEE  " + c(ANSI.dim, "(no local private key)"));

  const width = Math.max(...lines.map((l) => stripAnsi(l).length));
  const horiz = "─".repeat(width + 2);
  console.log("  ┌" + horiz + "┐");
  for (const line of lines) {
    const pad = " ".repeat(width - stripAnsi(line).length);
    console.log("  │ " + line + pad + " │");
  }
  console.log("  └" + horiz + "┘");
}

async function cmdSetup(): Promise<void> {
  printSetupHeader();

  const installerUrl =
    "https://raw.githubusercontent.com/okx/onchainos-skills/main/install.sh";

  // ── Step 1: onchainos binary ────────────────────────────────────────
  const adapter = new OnchainOsAdapter();
  if (!adapter.isInstalled()) {
    process.stdout.write("  " + c(ANSI.yellow, "⏳") + "  Installing onchainos binary…\n");
    process.stdout.write(
      "     " + c(ANSI.dim, `(via ${installerUrl})`) + "\n",
    );
    try {
      execSync(`curl -sSL --max-time 60 ${installerUrl} | sh`, {
        stdio: ["ignore", "ignore", "inherit"],
        env: { ...process.env, PATH: `${homedir()}/.local/bin:${process.env.PATH ?? ""}` },
      });
      process.env.PATH = `${homedir()}/.local/bin:${process.env.PATH ?? ""}`;
      console.log("  " + c(ANSI.green, "✓") + "  onchainos installed");
    } catch {
      console.error("\n  " + c(ANSI.red, "✗") + "  onchainos install failed.");
      console.error("     Install manually then re-run setup:");
      console.error("     " + c(ANSI.dim, `curl -sSL ${installerUrl} | sh`));
      process.exit(1);
    }
  } else {
    console.log("  " + c(ANSI.green, "✓") + "  onchainos detected");
  }

  // ── Step 2: already logged in? ──────────────────────────────────────
  const detection = await detectOnchainosWallet();
  if (detection.kind === "ok") {
    console.log("  " + c(ANSI.green, "✓") + "  Already signed in");
    console.log();
    printSetupSummary(detection.address, detection.email);
    console.log();
    console.log(
      "  " + c(ANSI.cyan, "→") + "  Restart OpenClaw: " + c(ANSI.bold, "openclaw gateway restart"),
    );
    console.log();
    return;
  }
  console.log();

  // ── Step 3: collect email ───────────────────────────────────────────
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  let email: string;
  try {
    email = (await rl.question("  " + c(ANSI.cyan, "→") + "  Email: ")).trim();
  } finally {
    rl.close();
  }
  if (!email.includes("@")) {
    console.error("  " + c(ANSI.red, "✗") + `  "${email}" doesn't look like an email address.`);
    process.exit(1);
  }

  // ── Step 4: send OTP (capture JSON output) ──────────────────────────
  const bin = resolveOnchainosBin();
  process.stdout.write("  " + c(ANSI.yellow, "⏳") + "  Sending login code to " + email + "…");
  try {
    execFileSync(bin, ["wallet", "login", email], { stdio: ["ignore", "pipe", "pipe"] });
  } catch {
    process.stdout.write(
      "\r  " + c(ANSI.red, "✗") + "  Could not send code. Check the address and try again.\n",
    );
    process.exit(1);
  }
  process.stdout.write(
    "\r  " + c(ANSI.green, "✓") + "  Code sent — check your inbox at " + c(ANSI.bold, email) + "\n",
  );
  console.log();

  // ── Step 5: collect OTP ─────────────────────────────────────────────
  const rlOtp = createInterface({ input: process.stdin, output: process.stdout });
  let otp: string;
  try {
    otp = (await rlOtp.question("  " + c(ANSI.cyan, "→") + "  Login code: ")).trim();
  } finally {
    rlOtp.close();
  }
  if (!/^\d{4,8}$/.test(otp)) {
    console.error(
      "  " + c(ANSI.red, "✗") + `  "${otp}" doesn't look like a code (expected 4-8 digits).`,
    );
    process.exit(1);
  }

  // ── Step 6: verify ──────────────────────────────────────────────────
  process.stdout.write("  " + c(ANSI.yellow, "⏳") + "  Verifying code…");
  try {
    execFileSync(bin, ["wallet", "verify", otp], { stdio: ["ignore", "pipe", "pipe"] });
  } catch {
    process.stdout.write(
      "\r  " + c(ANSI.red, "✗") + "  Verification failed. Re-run setup for a new code.\n",
    );
    process.exit(1);
  }
  process.stdout.write("\r  " + c(ANSI.green, "✓") + "  Verified                                \n");

  // ── Step 7: re-detect + summary ─────────────────────────────────────
  const after = await detectOnchainosWallet();
  if (after.kind !== "ok") {
    console.error(
      "\n  " + c(ANSI.red, "✗") + `  Login completed but status check failed: ${after.kind}`,
    );
    console.error("     Run `onchainos wallet status` to diagnose.");
    process.exit(1);
  }

  console.log();
  printSetupSummary(after.address, after.email);
  console.log();
  console.log(
    "  " + c(ANSI.cyan, "→") + "  Restart OpenClaw: " + c(ANSI.bold, "openclaw gateway restart"),
  );
  console.log();
}

async function cmdCache(port: number): Promise<void> {
  try {
    const data = (await queryProxy("/cache", port)) as Record<string, unknown>;
    console.log(`\nCache Stats\n`);
    for (const [key, value] of Object.entries(data)) {
      console.log(`  ${key}: ${JSON.stringify(value)}`);
    }
    console.log();
  } catch {
    console.error(`✗ Cannot connect to XClawRouter on port ${port}`);
    process.exit(1);
  }
}

function parseArgs(args: string[]): {
  version: boolean;
  help: boolean;
  doctor: boolean;
  logs: boolean;
  logsDays: number;
  partners: boolean;
  partnersTest: boolean;
  report: boolean;
  reportPeriod: "daily" | "weekly" | "monthly";
  reportJson: boolean;
  walletRecover: boolean;
  setup: boolean;
  chain?: "solana" | "base";
  port?: number;
  // Query commands
  queryStatus: boolean;
  queryWallet: boolean;
  queryModels: boolean;
  queryStats: boolean;
  queryStatsDays: number;
  queryCache: boolean;
} {
  const result = {
    version: false,
    help: false,
    doctor: false,
    logs: false,
    logsDays: 1,
    partners: false,
    partnersTest: false,
    report: false,
    reportPeriod: "daily" as "daily" | "weekly" | "monthly",
    reportJson: false,
    walletRecover: false,
    setup: false,
    chain: undefined as "solana" | "base" | undefined,
    port: undefined as number | undefined,
    queryStatus: false,
    queryWallet: false,
    queryModels: false,
    queryStats: false,
    queryStatsDays: 7,
    queryCache: false,
  };

  for (let i = 0; i < args.length; i++) {
    const arg = args[i];
    if (arg === "--version" || arg === "-v") {
      result.version = true;
    } else if (arg === "--help" || arg === "-h") {
      result.help = true;
    } else if (arg === "status") {
      result.queryStatus = true;
    } else if (arg === "models") {
      result.queryModels = true;
    } else if (arg === "stats") {
      result.queryStats = true;
      if (args[i + 1] === "--days" && args[i + 2]) {
        result.queryStatsDays = Math.min(parseInt(args[i + 2], 10) || 7, 30);
        i += 2;
      }
    } else if (arg === "cache") {
      result.queryCache = true;
    } else if (arg === "doctor" || arg === "--doctor") {
      result.doctor = true;
    } else if (arg === "logs") {
      result.logs = true;
      if (args[i + 1] === "--days" && args[i + 2]) {
        result.logsDays = parseInt(args[i + 2], 10) || 1;
        i += 2;
      }
    } else if (arg === "partners") {
      result.partners = true;
      if (args[i + 1] === "test") {
        result.partnersTest = true;
        i++;
      }
    } else if (arg === "report") {
      result.report = true;
      const next = args[i + 1];
      if (next && ["daily", "weekly", "monthly"].includes(next)) {
        result.reportPeriod = next as "daily" | "weekly" | "monthly";
        i++;
        if (args[i + 1] === "--json") {
          result.reportJson = true;
          i++;
        }
      } else if (next === "--json") {
        result.reportJson = true;
        i++;
      }
    } else if (arg === "wallet") {
      if (args[i + 1] === "recover") {
        result.walletRecover = true;
        i++;
      } else if (args[i + 1] === "solana" || args[i + 1] === "base") {
        result.chain = args[i + 1] as "solana" | "base";
        i++;
      } else {
        result.queryWallet = true;
      }
    } else if (
      (arg === "chain" || arg === "/wallet") &&
      (args[i + 1] === "solana" || args[i + 1] === "base")
    ) {
      result.chain = args[i + 1] as "solana" | "base";
      i++;
    } else if (arg === "setup") {
      result.setup = true;
    } else if (arg === "--port" && args[i + 1]) {
      result.port = parseInt(args[i + 1], 10);
      i++;
    }
  }

  return result;
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));

  if (args.version) {
    console.log(VERSION);
    process.exit(0);
  }

  if (args.help) {
    printHelp();
    process.exit(0);
  }

  // Query commands — talk to running proxy
  const queryPort = args.port ?? getProxyPort();

  if (args.queryStatus) {
    await cmdStatus(queryPort);
    process.exit(0);
  }
  if (args.queryWallet) {
    await cmdWallet(queryPort);
    process.exit(0);
  }
  if (args.queryModels) {
    await cmdModels(queryPort);
    process.exit(0);
  }
  if (args.queryStats) {
    await cmdStats(queryPort, args.queryStatsDays);
    process.exit(0);
  }
  if (args.queryCache) {
    await cmdCache(queryPort);
    process.exit(0);
  }

  if (args.doctor) {
    // Parse: doctor [opus|sonnet] [question...]
    const rawArgs = process.argv.slice(2);
    const doctorIndex = rawArgs.findIndex((a) => a === "doctor" || a === "--doctor");
    const afterDoctor = rawArgs.slice(doctorIndex + 1);

    // Check if first arg is model selection
    let model: "sonnet" | "opus" = "sonnet"; // default to cheaper
    let questionArgs = afterDoctor;

    if (afterDoctor[0] === "opus") {
      model = "opus";
      questionArgs = afterDoctor.slice(1);
    } else if (afterDoctor[0] === "sonnet") {
      model = "sonnet";
      questionArgs = afterDoctor.slice(1);
    }

    const userQuestion = questionArgs.join(" ").trim() || undefined;
    await runDoctor(userQuestion, model);
    process.exit(0);
  }

  if (args.logs) {
    const output = await formatRecentLogs(args.logsDays);
    console.log(output);
    process.exit(0);
  }

  if (args.partners) {
    if (PARTNER_SERVICES.length === 0) {
      console.log("No partner APIs available.");
      process.exit(0);
    }

    console.log(`\nClawRouter Partner APIs (v${VERSION})\n`);

    // Compact grouped view — one line per tool, grouped by category.
    const byCategory = new Map<string, typeof PARTNER_SERVICES>();
    for (const svc of PARTNER_SERVICES) {
      const bucket = byCategory.get(svc.category) ?? [];
      bucket.push(svc);
      byCategory.set(svc.category, bucket);
    }
    const toolWidth = Math.max(...PARTNER_SERVICES.map((s) => `blockrun_${s.id}`.length), 28);
    const priceWidth = Math.max(
      ...PARTNER_SERVICES.map((s) =>
        s.pricing.perUnit === "free" ? 4 : `${s.pricing.perUnit}/${s.pricing.unit}`.length,
      ),
      12,
    );
    for (const [category, services] of byCategory) {
      console.log(`${category}`);
      for (const svc of services) {
        const tool = `blockrun_${svc.id}`.padEnd(toolWidth);
        const price = (
          svc.pricing.perUnit === "free" ? "free" : `${svc.pricing.perUnit}/${svc.pricing.unit}`
        ).padEnd(priceWidth);
        console.log(`  ${tool}  ${price}  ${svc.shortDescription}`);
      }
      console.log();
    }

    if (args.partnersTest) {
      console.log("Testing partner endpoints...\n");
      const apiBase = "https://blockrun.ai/api";
      for (const svc of PARTNER_SERVICES) {
        const url = `${apiBase}/v1${svc.proxyPath}`;
        try {
          const response = await fetch(url, { method: "GET" });
          const status = response.status;
          const ok = status === 402 ? "alive (402 = payment required)" : `status ${status}`;
          console.log(`  ${svc.id}: ${ok}`);
        } catch (err) {
          console.log(`  ${svc.id}: error - ${err instanceof Error ? err.message : String(err)}`);
        }
      }
      console.log();
    }

    process.exit(0);
  }

  if (args.walletRecover) {
    await recoverWalletFromMnemonic();
    process.exit(0);
  }

  if (args.chain) {
    const targetChain = args.chain;

    if (targetChain === "solana") {
      // Ensure Solana wallet is set up (mnemonic → keypair)
      const { existsSync } = await import("fs");
      const { MNEMONIC_FILE, setupSolana } = await import("./auth.js");
      const { deriveSolanaKeyBytes, getSolanaAddress } = await import("./wallet.js");

      let solanaAddr: string;
      if (existsSync(MNEMONIC_FILE)) {
        // Already set up — derive address from existing mnemonic
        const { readFileSync } = await import("fs");
        const mnemonic = readFileSync(MNEMONIC_FILE, "utf8").trim();
        const keyBytes = deriveSolanaKeyBytes(mnemonic);
        solanaAddr = await getSolanaAddress(keyBytes);
        console.log(`[XClawRouter] Solana wallet already set up.`);
      } else {
        // First time — generate mnemonic + keypair
        console.log(`[XClawRouter] Setting up Solana wallet...`);
        const { solanaPrivateKeyBytes } = await setupSolana();
        solanaAddr = await getSolanaAddress(solanaPrivateKeyBytes);
        console.log(`[XClawRouter] Solana wallet created.`);
        console.log(`[XClawRouter] ⚠  Back up your mnemonic: ${MNEMONIC_FILE}`);
      }

      await savePaymentChain("solana");
      console.log(`[XClawRouter] Payment chain → Solana`);
      console.log(`[XClawRouter] Solana address : ${solanaAddr}`);
      console.log(`[XClawRouter] Fund USDC at   : https://solscan.io/account/${solanaAddr}`);
    } else {
      await savePaymentChain("base");
      console.log(`[XClawRouter] Payment chain → Base (EVM)`);
    }

    console.log(
      `[XClawRouter] Restart gateway to apply: systemctl --user restart openclaw-gateway.service`,
    );
    console.log(`[XClawRouter]   or: openclaw gateway restart`);
    process.exit(0);
  }

  if (args.report) {
    const report = await generateReport(args.reportPeriod, args.reportJson);
    console.log(report);
    process.exit(0);
  }

  if (args.setup) {
    await cmdSetup();
    process.exit(0);
  }

  // Resolve wallet key.
  //
  // On a fresh install with no OKX wallet, `resolveOrGenerateWalletKey`
  // throws `OnchainOsRequiredError` instead of silently generating a local
  // key. In an INTERACTIVE terminal we transparently run `cmdSetup` here so
  // a user typing `npx @blockrun/xclawrouter` for the first time gets walked
  // through OKX install + email + OTP without having to manually invoke a
  // second command. In NON-interactive contexts (CI, Docker, gateway daemon)
  // we keep the old error+exit-2 behaviour so automation isn't left hanging
  // on a stdin prompt that no one will ever answer.
  let wallet;
  try {
    wallet = await resolveOrGenerateWalletKey();
  } catch (err) {
    if (err instanceof OnchainOsRequiredError) {
      const interactive = Boolean(process.stdin.isTTY && process.stdout.isTTY);
      if (interactive) {
        console.log("\n[XClawRouter] No wallet detected — launching guided setup\n");
        await cmdSetup();
        // cmdSetup either exits non-zero on failure or finishes the OKX
        // login. Re-resolve and continue starting the proxy.
        wallet = await resolveOrGenerateWalletKey();
      } else {
        console.error(`[XClawRouter] ${err.message}`);
        process.exit(2);
      }
    } else {
      throw err;
    }
  }

  // Agentic Wallet status block. Tells the user, on every launch, whether
  // onchainos is installed and what their login state is, with the literal
  // next-step command/URL. Emitted BEFORE the "Using ... wallet:" line so the
  // user understands the state of the option they're (likely) not on, before
  // we tell them which local fallback we picked. XCLAW_QUIET=1 silences it.
  // (`src/index.ts` emits the same block through OpenClaw's structured
  // logger — keep these two sites in sync when changing the block shape.)
  const quiet = process.env.XCLAW_QUIET === "1";
  const detection = wallet.onchainosDetection;
  let printedStatus = false;
  if (!quiet && detection) {
    const lines = formatAgenticWalletStatus(detection);
    for (const line of lines) {
      // CLI uses one stream (stdout); the `level` distinction matters for
      // structured loggers, not for terminals, so funnel everything through
      // console.log with the consistent [XClawRouter] prefix.
      console.log(`[XClawRouter] ${line.text}`);
    }
    printedStatus = lines.length > 0;
  }

  if (wallet.source === "okx") {
    console.log(
      `[XClawRouter] Using OKX onchainos wallet: ${wallet.address}${wallet.email ? ` (${wallet.email})` : ""}`,
    );
  } else if (wallet.source === "generated") {
    console.log(`[XClawRouter] Generated new wallet: ${wallet.address}`);
  } else if (wallet.source === "saved") {
    console.log(`[XClawRouter] Using saved wallet: ${wallet.address}`);
  } else if (wallet.source === "config") {
    console.log(`[XClawRouter] Using wallet from plugin config: ${wallet.address}`);
  } else {
    console.log(`[XClawRouter] Using wallet from BLOCKRUN_WALLET_KEY: ${wallet.address}`);
  }

  // Suppression hint only when we actually emitted a status block — so a
  // running OKX wallet doesn't end up with a dangling "(set XCLAW_QUIET…)".
  if (printedStatus) {
    console.log(`[XClawRouter]   (set XCLAW_QUIET=1 to suppress this block)`);
  }

  // Show Solana address if available
  if (wallet.solanaPrivateKeyBytes) {
    try {
      const solAddr = await getSolanaAddress(wallet.solanaPrivateKeyBytes);
      console.log(`[XClawRouter] Solana address: ${solAddr}`);
    } catch {
      // Non-fatal
    }
  }

  // Start the proxy
  const proxy = await startProxy({
    wallet,
    port: args.port,
    onReady: (port) => {
      console.log(`[XClawRouter] v${VERSION} | Proxy listening on http://127.0.0.1:${port}`);
      console.log(`[XClawRouter] Health check: http://127.0.0.1:${port}/health`);
    },
    onError: (error) => {
      console.error(`[XClawRouter] Error: ${error.message}`);
    },
    onRouted: (decision) => {
      const cost = decision.costEstimate.toFixed(4);
      const saved = (decision.savings * 100).toFixed(0);
      console.log(`[XClawRouter] [${decision.tier}] ${decision.model} $${cost} (saved ${saved}%)`);
    },
    onLowBalance: (info) => {
      console.warn(`[XClawRouter] Low balance: ${info.balanceUSD}. Fund: ${info.walletAddress}`);
    },
    onInsufficientFunds: (info) => {
      console.error(
        `[XClawRouter] Insufficient funds. Balance: ${info.balanceUSD}, Need: ${info.requiredUSD}`,
      );
      console.error(`[XClawRouter] Need help? Run: npx @blockrun/xclawrouter doctor`);
    },
  });

  // Check balance on the active payment chain
  const paymentChain = await resolvePaymentChain();
  const displayAddress =
    paymentChain === "solana" && proxy.solanaAddress ? proxy.solanaAddress : wallet.address;
  try {
    const balance = await proxy.balanceMonitor.checkBalance();
    if (balance.isEmpty) {
      console.log(`[XClawRouter] Wallet balance: $0.00 (using FREE model)`);
      console.log(`[XClawRouter] Fund wallet for premium models: ${displayAddress}`);
    } else if (balance.isLow) {
      console.log(`[XClawRouter] Wallet balance: ${balance.balanceUSD} (low)`);
    } else {
      console.log(`[XClawRouter] Wallet balance: ${balance.balanceUSD}`);
    }
    // Invalidate after display so the first real request always gets a fresh check.
    // Prevents a flaky RPC at startup from caching a false $0.00 and triggering
    // free-model fallback on the first request.
    proxy.balanceMonitor.invalidate();
  } catch {
    console.log(`[XClawRouter] Wallet: ${displayAddress} (balance check pending)`);
  }

  console.log(`[XClawRouter] Ready - Ctrl+C to stop`);

  // Handle graceful shutdown
  const shutdown = async (signal: string) => {
    console.log(`\n[XClawRouter] Received ${signal}, shutting down...`);
    try {
      await proxy.close();
      console.log(`[XClawRouter] Proxy closed`);
      process.exit(0);
    } catch (err) {
      console.error(`[XClawRouter] Error during shutdown: ${err}`);
      process.exit(1);
    }
  };

  process.on("SIGINT", () => shutdown("SIGINT"));
  process.on("SIGTERM", () => shutdown("SIGTERM"));

  // Keep process alive
  await new Promise(() => {});
}

main().catch((err) => {
  console.error(`[XClawRouter] Fatal error: ${err.message}`);
  console.error(`[XClawRouter] Need help? Run: npx @blockrun/xclawrouter doctor`);
  process.exit(1);
});
